on:
  workflow_call:

jobs:
  checks:
    name: Linter & Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Poetry Install
        run: poetry install
        
      - name: Linter
        run: |
          poetry run black --check .
          poetry run flake8
          
      - name: Tests
        run: |
          poetry run pytest
