on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      workdir:
        description: "Working directory."
        type: string
        required: false
        default: "."
      release_suffix:
        description: "Suffix (a.k.a build metadata) appended by semantic-release to the version number."
        required: false
        type: string
        default: ""
      release_vcs:
        description: "If true, a Github release will be published."
        required: false
        type: boolean
        default: false
      release_commit:
        description: "If true, the release commit will be created."
        required: false
        type: boolean
        default: false
      release_tag:
        description: "If true, the release tag will be created."
        required: false
        type: boolean
        default: false
      release_changelog:
        description: "If true, the changelog will be updated."
        required: false
        type: boolean
        default: false
      release_build:
        description: "If true, the package will be built."
        required: false
        type: boolean
        default: false
      publish:
        description: "If true, the package will be published to the target repository."
        required: false
        type: boolean
        default: false
      publish_repository:
        description: "Poetry repository to publish to. The target repository should be configured poetry.toml."
        required: false
        type: string
      publish_project_id:
        description: "GC project ID."
        required: false
        type: string
      publish_project_number:
        description: "GC project number, not the project ID."
        required: false
        type: string

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.workdir }}

    permissions:
      contents: "write"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0

      - name: Setup Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Poetry install
        run: poetry install

      - name: Poetry key-ring
        run: poetry self add keyrings.google-artifactregistry-auth

      - name: Semantic Release Setup
        run: |
          git config --global user.name "Semantic Release"
          git config --global user.email "github@digitlcloud.com"

      - name: Python Semantic Release
        run: |
          params=()
          if [[ ${{ inputs.release_vcs }} == false ]]; then
            params+=("--no-vcs-release")
          fi
          if [[ ${{ inputs.release_commit }} == false ]]; then
            params+=("--no-commit")
          fi
          if [[ ${{ inputs.release_tag }} == false ]]; then
            params+=("--no-tag")
          fi
          if [[ ${{ inputs.release_changelog }} == false ]]; then
            params+=("--no-changelog")
          fi
          if [[ ${{ inputs.release_build }} == false ]]; then
            params+=("--skip-build")
          fi
          poetry run semantic-release -v version \
            --build-metadata ${{ inputs.release_suffix }} \
            "${params[@]}"

      - name: Authenticate to Google Cloud
        if: inputs.publish == true
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ inputs.publish_project_number }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-actions@${{ inputs.publish_project_id }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        if: inputs.publish == true
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Poetry publish
        if: inputs.publish == true
        run: poetry publish --build -r ${{ inputs.publish_repository }} --skip-existing
