name: "Manual Poetry Update, Commit & Push"

on:
  workflow_call:

jobs:
  commit:
    name: Manual Poetry Update, Commit & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Poetry Install
        run: poetry install

      - name: Update dependencies
        run: poetry update
  
      - name: Run Tests
        run: poetry run pytest

      - uses: actions/checkout@master
        with:
          persist-credentials: false 
          fetch-depth: 0 
      - name: Create local changes
        run: |
          git pull --rebase
          git add .
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          message: "perf: update poetry dependencies"
