on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true
    inputs:
      workdir:
        type: string
        required: false
        default: "."
      publish:
        description: "If true, the package will be published to the target repository."
        required: false
        type: boolean
        default: false
      repository:
        description: "Poetry repository to publish to. The target repository should be configured in the poetry.toml file."
        required: false
        type: string
      project_id:
        description: "GC project ID."
        required: false
        type: string
      project_number:
        description: "GC project number, not the project ID."
        required: false
        type: string
      transient_semantic_release_version:
        description: "If true, `semantic release version` will be run, without committing or triggering a release."
        required: false
        type: boolean
        default: false
    outputs:
      version:
        value: ${{ jobs.release.outputs.version }}

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    name: Semantic Release
    runs-on: ubuntu-latest

    permissions:
      contents: "write"
      id-token: "write"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Poetry
        run: pipx install poetry

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Change directory
        run: cd ${{ inputs.workdir }}

      - name: Poetry install
        run: poetry install

      - name: Poetry key-ring
        run: poetry self add keyrings.google-artifactregistry-auth

      - name: Semantic Release Setup
        run: |
          git config --global user.name "Semantic Release"
          git config --global user.email "github@digitlcloud.com"

      - name: Set version output
        id: set_version
        run: |
          if [[ ${{ inputs.transient_semantic_release_version}} == false ]]; then
            echo "Setting version output..."
            echo "version=$(poetry run semantic-release version --print)"
            echo "version=$(poetry run semantic-release version --print)" >> $GITHUB_OUTPUT
          else
            echo "Setting transient version output..."
            suffix=$(git branch --show-current | sed 's/feat\///')_$(git rev-parse --short HEAD)
            echo "version=$(poetry run semantic-release version --build-metadata $suffix --print)"
            echo "version=$(poetry run semantic-release version --build-metadata $suffix --print)" >> $GITHUB_OUTPUT
          fi

      - name: Python Semantic Release
        if: inputs.transient_semantic_release_version == false
        run: |
          poetry run semantic-release -v version --skip-build

      - name: Python Semantic Release (transient)
        if: inputs.transient_semantic_release_version == true
        run: |
          suffix=$(git branch --show-current | sed 's/feat\///')_$(git rev-parse --short HEAD)
          poetry run semantic-release -v version \
            --no-vcs-release \
            --no-commit \
            --skip-build \
            --build-metadata $suffix

      - name: Authenticate to Google Cloud
        if: inputs.publish == true
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/${{ inputs.project_number }}/locations/global/workloadIdentityPools/github-actions/providers/github-actions"
          service_account: "github-actions@${{ inputs.project_id }}.iam.gserviceaccount.com"

      - name: Set up Cloud SDK
        if: inputs.publish == true
        uses: "google-github-actions/setup-gcloud@v2"

      - name: Poetry publish
        if: inputs.publish == true
        run: poetry publish --build -r ${{ inputs.repository }} --skip-existing

    outputs:
      version: ${{ steps.set_version.outputs.version }}
