on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

jobs:
  commit:
    name: Manual Poetry Update, Commit & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - uses: actions/checkout@master
        with:
          persist-credentials: false 
          fetch-depth: 0 

      - name: Poetry Install
        run: poetry install

      - name: Update dependencies
        run: poetry update
  
      - name: Run Tests
        run: poetry run pytest

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          branch: main
          message: "perf: update poetry dependencies"
