on:
  workflow_call:
    inputs:
      workdir:
        type: string
        required: false
        default: "."
      black:
        type: boolean
        required: false
        default: false
      flake8:
        type: boolean
        required: false
        default: false
      ruff:
        type: boolean
        required: false
        default: false
      pyright:
        type: boolean
        required: false
        default: false
      pytest:
        type: boolean
        required: false
        default: false

jobs:
  checks:
    name: Linter & Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.workdir }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Poetry Install
        run: poetry install

      - if: inputs.black == true
        name: black
        run: poetry run black --check .

      - if: inputs.flake8 == true
        name: flake8
        run: poetry run flake8

      - if: inputs.ruff == true
        name: ruff
        run: poetry run ruff check .

      - if: inputs.pyright == true
        name: pyright
        run: poetry run pyright

      - if: inputs.pytest == true
        name: pytest
        run: poetry run pytest
