on:
  workflow_call:
    secrets:
      GH_TOKEN:
        required: true

env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  commit:
    name: Manual Poetry Update, Commit & Push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "poetry"

      - name: Poetry Install
        run: poetry install

      - name: Update dependencies
        run: poetry update
  
      - name: Run Tests
        run: poetry run pytest

      - uses: actions/checkout@master
        with:
          persist-credentials: false 
          fetch-depth: 0 
      # - name: Create local changes
      #   run: |
      #     git add .
      #   env:
      #     GITHUB_TOKEN: $GH_TOKEN
      - name: Where are we?
        run: |
          ls -la
          pwd
        env:
          GITHUB_TOKEN: $GH_TOKEN
      # - name: Commit & Push changes
      #   uses: actions-js/push@master
      #   with:
      #     github_token: $GH_TOKEN
      #     branch: main
      #     message: "perf: update poetry dependencies"
